k8s-workload-streamprocessing:
  wl_obj_name: vss-vios-streamprocessing
  port: 4005
  enable: true
  WDM_CONSUMER_GRP_ID: sdr-streamprocessing-vios-cg
  WDM_REDIS_CACHE_OBJECT: streamprocessing-data
  WDM_XDS_USE_POD_DNS: true
  WDM_XDS_USE_IP_ADDRESS: false
  WDM_REDIS_MSG_KEY: vst.event
  REDIS_MSG_KEY: vst.event
  WDM_REAPPLY_ON_WL_RESTART: true
  WDM_CLUSTER_TYPE: k8s
  WDM_CLUSTER_CONTAINER_NAMES: '["vss-vios-streamprocessing"]'
  WDM_KFK_BOOTSTRAP_URL: kafka-kafka:9092
  WDM_INITIALIZE_FROM_VST: false
  WDM_WL_ADD_URL: /api/v1/proxy/stream/add
  WDM_WL_DELETE_URL: /api/v1/proxy/stream/
  WDM_WL_CHANGE_ID_ADD: camera_proxy
  WDM_WL_CHANGE_ID_DEL: camera_remove
  WDM_WL_HEALTH_CHECK_URL: /api/v1/proxy/configuration
  WDM_WL_THRESHOLD: 100
  WDM_CONTROLLER_REPROVISION: true
  WDM_RESET_ON_WLOBJ_CRASH: false
  WDM_CLEAR_DATA_WL: true
  WDM_KFK_ENABLE: false
  WDM_MSG_TOPIC: vst_events
  WDM_DS_SWAP_ID_NAME: false
  WDM_ADD_REMOVE_RETRY_ATTEMPTS: 50
  WDM_DISABLE_WERKZEUG_LOGGING: true
  WDM_WL_OBJECT_NAME: vss-vios-streamprocessing
  VST_STREAMS_ENDPOINT: http://vss-vios-sensor:30000/api/v1/sensor/streams
  VST_STATUS_ENDPOINT: http://vss-vios-sensor:30000/api/v1/sensor/status
  OTEL_SDK_DISABLED: true
  OTEL_SERVICE_NAME: SDR_AGENT
  WDM_WL_NAME_IGNORE_REGEX: ""
  WDM_TARGET_PORT_MAPPING: '{"vss-vios-streamprocessing": 30001}'
  ENVOY_ROUTE_HEADER: streamid
  WDM_MS_LISTENER_PORT: 10000
  NOHEADERTARGETROUTE: true
  HEADERLESS_SERVICE_ENDPOINTS: '["vss-vios-streamprocessing:30001"]'
  WDM_WL_REDIS_MSG_FIELD: sensor.id
  WDM_MSG_KEY: vst_events
  WDM_WL_PROXY_URL: /
  ENVOY_ROUTE_URL_PREFIX_REWRITE: /
  ENVOY_ROUTE_URL_PREFIX: /
  ENVOY_REQUEST_TIMEOUT: "30"
  ENVOYROUTEHEADER: streamid
