# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  cosmos-reason2-8b:
    image: nvcr.io/nvstaging/nim/cosmos-reason2-8b:1.7.1.rc0-49630198
    container_name: nvidia-cosmos-reason2-8b
    profiles:
    - vlm_local_cosmos-reason2-8b
    runtime: nvidia
    shm_size: 32gb
    ports:
     - ${VLM_PORT:-30082}:8000
    environment:
      NGC_API_KEY: "${NGC_CLI_API_KEY}"
      NIM_MODEL_NAME: "${VLM_CUSTOM_WEIGHTS:-}"
      VLM_NIM_KVCACHE_PERCENT: "${VLM_NIM_KVCACHE_PERCENT}"
    env_file:
      - ${VSS_APPS_DIR}/services/nim/cosmos-reason2-8b/hw-${HARDWARE_PROFILE}.env
      - ${VLM_ENV_FILE:-${VSS_APPS_DIR}/services/nim/fallback-override.env}
    volumes:
      - cosmos_reason2_8b_cache:/opt/nim/.cache
      - type: bind
        source: ${VLM_CUSTOM_WEIGHTS:-}
        target: ${VLM_CUSTOM_WEIGHTS:-/nan}
        bind:
          create_host_path: false
    user: "${UID:-1000}:${GID:-1000}"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
              driver: nvidia
              device_ids:
              - "${VLM_DEVICE_ID:-0}"
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'if [ -f /tmp/ready_done ]; then curl --max-time 30 -f http://localhost:8000/v1/health/live; else elapsed=0; while ! curl -fs http://localhost:8000/v1/health/ready > /dev/null 2>&1; do sleep 5; echo "elapsed $$elapsed"; elapsed=$$((elapsed + 5)); if [ $$elapsed -ge 600 ]; then echo "Service did not become ready within 10 minutes"; exit 1; fi; done; touch /tmp/ready_done && curl --max-time 30 -f http://localhost:8000/v1/health/live; fi']
      interval: 60s
      timeout: 650s
      retries: 2

  cosmos-reason2-8b-shared-gpu:
    image: nvcr.io/nvstaging/nim/cosmos-reason2-8b:1.7.1.rc0-49630198
    container_name: nvidia-cosmos-reason2-8b
    profiles:
    - vlm_local_shared_cosmos-reason2-8b
    runtime: nvidia
    shm_size: 32gb
    ports:
     - ${VLM_PORT:-30082}:8000
    environment:
      NGC_API_KEY: "${NGC_CLI_API_KEY}"
      NIM_MODEL_NAME: "${VLM_CUSTOM_WEIGHTS:-}"
    env_file:
      - ${VSS_APPS_DIR}/services/nim/cosmos-reason2-8b/hw-${HARDWARE_PROFILE}-shared.env
      - ${VLM_ENV_FILE:-${VSS_APPS_DIR}/services/nim/fallback-override.env}
    volumes:
      - cosmos_reason2_8b_cache:/opt/nim/.cache
      - type: bind
        source: ${VLM_CUSTOM_WEIGHTS:-}
        target: ${VLM_CUSTOM_WEIGHTS:-/nan}
        bind:
          create_host_path: false
    user: "${UID:-1000}:${GID:-1000}"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
              driver: nvidia
              device_ids:
              - "${SHARED_LLM_VLM_DEVICE_ID:-${VLM_DEVICE_ID:-0}}"
    restart: always

    healthcheck:
      test: ['CMD-SHELL', 'if [ -f /tmp/ready_done ]; then curl --max-time 30 -f http://localhost:8000/v1/health/live; else elapsed=0; while ! curl -fs http://localhost:8000/v1/health/ready > /dev/null 2>&1; do sleep 5; echo "elapsed $$elapsed"; elapsed=$$((elapsed + 5)); if [ $$elapsed -ge 600 ]; then echo "Service did not become ready within 10 minutes"; exit 1; fi; done; touch /tmp/ready_done && curl --max-time 30 -f http://localhost:8000/v1/health/live; fi']
      interval: 60s
      timeout: 650s
      retries: 2
volumes:
  cosmos_reason2_8b_cache: