# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:

  vss-ui:
    image: nvcr.io/nvstaging/vss-core/vss-agent-ui:3.2.0-26.05.2-3ab18ca37ffb
    profiles: ["bp_wh_2d","bp_developer_base_2d","bp_developer_search_2d","bp_developer_lvs_2d","bp_developer_alerts_2d_cv", "bp_developer_alerts_2d_vlm"]
    container_name: vss-agent-ui
    ports:
      - 3000:3000
    restart: always
    depends_on:
      vss-agent:
        condition: service_healthy
    environment:
      RUN_APP_NAME: nv-metropolis-bp-vss-ui
      NEXT_PUBLIC_APP_TITLE: '${NEXT_PUBLIC_APP_TITLE:-VSS BLUEPRINT}'
      NEXT_PUBLIC_APP_SUBTITLE: '${NEXT_PUBLIC_APP_SUBTITLE:-VISION}'
      # === App wide chat sidebar ===
      NEXT_PUBLIC_ENABLE_CHAT_SIDEBAR: ${NEXT_PUBLIC_ENABLE_CHAT_SIDEBAR:-true}
      NEXT_PUBLIC_CHAT_SIDEBAR_OPEN_DEFAULT: ${NEXT_PUBLIC_CHAT_SIDEBAR_OPEN_DEFAULT:-false}
      NEXT_PUBLIC_SIDEBAR_CHAT_WORKFLOW: ${NEXT_PUBLIC_SIDEBAR_CHAT_WORKFLOW:-Vision Agent}
      NEXT_PUBLIC_SIDEBAR_CHAT_WEBSOCKET_CHAT_COMPLETION_URL: ${VSS_PUBLIC_WS_PROTOCOL}://${VSS_PUBLIC_HOST}:${VSS_PUBLIC_PORT}/websocket
      NEXT_PUBLIC_SIDEBAR_CHAT_HTTP_CHAT_COMPLETION_URL: http://${HOST_IP}:${VSS_AGENT_PORT:-8000}/chat/stream
      NEXT_PUBLIC_SIDEBAR_CHAT_WEB_SOCKET_DEFAULT_ON: ${NEXT_PUBLIC_SIDEBAR_CHAT_WEB_SOCKET_DEFAULT_ON:-false}
      NEXT_PUBLIC_SIDEBAR_CHAT_CHAT_HISTORY_DEFAULT_ON: ${NEXT_PUBLIC_SIDEBAR_CHAT_CHAT_HISTORY_DEFAULT_ON:-true}
      NEXT_PUBLIC_SIDEBAR_CHAT_ENABLE_INTERMEDIATE_STEPS: ${NEXT_PUBLIC_SIDEBAR_CHAT_ENABLE_INTERMEDIATE_STEPS:-true}
      NEXT_PUBLIC_SIDEBAR_CHAT_DARK_THEME_DEFAULT: ${NEXT_PUBLIC_SIDEBAR_CHAT_DARK_THEME_DEFAULT:-true}
      NEXT_PUBLIC_SIDEBAR_CHAT_SIDE_CHATBAR_COLLAPSED: ${NEXT_PUBLIC_SIDEBAR_CHAT_SIDE_CHATBAR_COLLAPSED:-true}
      NEXT_PUBLIC_SIDEBAR_CHAT_AGENT_API_URL_BASE: ${VSS_PUBLIC_HTTP_PROTOCOL}://${VSS_PUBLIC_HOST}:${VSS_PUBLIC_PORT}/api/v1
      NEXT_PUBLIC_SIDEBAR_CHAT_CHAT_UPLOAD_FILE_ENABLE: ${NEXT_PUBLIC_SIDEBAR_CHAT_CHAT_UPLOAD_FILE_ENABLE:-true}
      NEXT_PUBLIC_SIDEBAR_CHAT_CHAT_INPUT_MIC_ENABLED: ${NEXT_PUBLIC_SIDEBAR_CHAT_CHAT_INPUT_MIC_ENABLED:-false}
      NEXT_PUBLIC_SIDEBAR_CHAT_INTERACTION_MODAL_CANCEL_ENABLED: ${NEXT_PUBLIC_SIDEBAR_CHAT_INTERACTION_MODAL_CANCEL_ENABLED:-false}
      NEXT_PUBLIC_SIDEBAR_CHAT_CHAT_MESSAGE_EDIT_ENABLED: ${NEXT_PUBLIC_SIDEBAR_CHAT_CHAT_MESSAGE_EDIT_ENABLED:-false}
      NEXT_PUBLIC_SIDEBAR_CHAT_CHAT_MESSAGE_SPEAKER_ENABLED: ${NEXT_PUBLIC_SIDEBAR_CHAT_CHAT_MESSAGE_SPEAKER_ENABLED:-false}
      NEXT_PUBLIC_SIDEBAR_CHAT_CHAT_MESSAGE_COPY_ENABLED: ${NEXT_PUBLIC_SIDEBAR_CHAT_CHAT_MESSAGE_COPY_ENABLED:-false}
      NEXT_PUBLIC_SIDEBAR_CHAT_CHAT_UPLOAD_FILE_METADATA_ENABLED: ${NEXT_PUBLIC_SIDEBAR_CHAT_CHAT_UPLOAD_FILE_METADATA_ENABLED:-false}
      NEXT_PUBLIC_SIDEBAR_CHAT_CHAT_UPLOAD_FILE_HIDDEN_MESSAGE_TEMPLATE: '${NEXT_PUBLIC_SIDEBAR_CHAT_CHAT_UPLOAD_FILE_HIDDEN_MESSAGE_TEMPLATE:-Let''s show the videos just uploaded {filenames}?}'
      NEXT_PUBLIC_SIDEBAR_CHAT_SHOW_THEME_TOGGLE_BUTTON: ${NEXT_PUBLIC_SIDEBAR_CHAT_SHOW_THEME_TOGGLE_BUTTON:-false}
      NEXT_PUBLIC_SIDEBAR_CHAT_CHAT_UPLOAD_FILE_CONFIG_TEMPLATE_JSON: ${NEXT_PUBLIC_SIDEBAR_CHAT_CHAT_UPLOAD_FILE_CONFIG_TEMPLATE_JSON:-{}}
      NEXT_PUBLIC_SIDEBAR_CHAT_CHAT_API_CUSTOM_AGENT_PARAMS_JSON: ${NEXT_PUBLIC_SIDEBAR_CHAT_CHAT_API_CUSTOM_AGENT_PARAMS_JSON:-{}}
      # === End app wide chat sidebar ===

      # === Chat Tab Configuration ===
      NEXT_PUBLIC_ENABLE_CHAT_TAB: ${NEXT_PUBLIC_ENABLE_CHAT_TAB:-false}
      NEXT_PUBLIC_WORKFLOW: '${NEXT_PUBLIC_WORKFLOW:-Vision Agent}'
      NEXT_PUBLIC_WEBSOCKET_CHAT_COMPLETION_URL: ${VSS_PUBLIC_WS_PROTOCOL}://${VSS_PUBLIC_HOST}:${VSS_PUBLIC_PORT}/websocket
      NEXT_PUBLIC_HTTP_CHAT_COMPLETION_URL: http://${HOST_IP}:${VSS_AGENT_PORT:-8000}/chat/stream
      NEXT_PUBLIC_WEB_SOCKET_DEFAULT_ON: ${NEXT_PUBLIC_WEB_SOCKET_DEFAULT_ON:-false}
      NEXT_PUBLIC_RIGHT_MENU_OPEN: ${NEXT_PUBLIC_RIGHT_MENU_OPEN:-false}
      NEXT_PUBLIC_ENABLE_INTERMEDIATE_STEPS: ${NEXT_PUBLIC_ENABLE_INTERMEDIATE_STEPS:-true}
      NEXT_PUBLIC_SHOW_THEME_TOGGLE_BUTTON: ${NEXT_PUBLIC_SHOW_THEME_TOGGLE_BUTTON:-false}
      NEXT_PUBLIC_DARK_THEME_DEFAULT: ${NEXT_PUBLIC_DARK_THEME_DEFAULT:-true}
      NEXT_PUBLIC_SIDE_CHATBAR_COLLAPSED: ${NEXT_PUBLIC_SIDE_CHATBAR_COLLAPSED:-true}
      NEXT_PUBLIC_CHAT_HISTORY_DEFAULT_ON: ${NEXT_PUBLIC_CHAT_HISTORY_DEFAULT_ON:-true}
      NEXT_PUBLIC_AGENT_API_URL_BASE: ${VSS_PUBLIC_HTTP_PROTOCOL}://${VSS_PUBLIC_HOST}:${VSS_PUBLIC_PORT}/api/v1
      NEXT_PUBLIC_CHAT_INPUT_MIC_ENABLED: ${NEXT_PUBLIC_CHAT_INPUT_MIC_ENABLED:-false}
      NEXT_PUBLIC_CHAT_MESSAGE_EDIT_ENABLED: ${NEXT_PUBLIC_CHAT_MESSAGE_EDIT_ENABLED:-false}
      NEXT_PUBLIC_CHAT_MESSAGE_SPEAKER_ENABLED: ${NEXT_PUBLIC_CHAT_MESSAGE_SPEAKER_ENABLED:-false}
      NEXT_PUBLIC_CHAT_MESSAGE_COPY_ENABLED: ${NEXT_PUBLIC_CHAT_MESSAGE_COPY_ENABLED:-false}
      NEXT_PUBLIC_INTERACTION_MODAL_CANCEL_ENABLED: ${NEXT_PUBLIC_INTERACTION_MODAL_CANCEL_ENABLED:-false}
      NEXT_PUBLIC_CHAT_UPLOAD_FILE_ENABLE: ${NEXT_PUBLIC_CHAT_UPLOAD_FILE_ENABLE:-true}
      NEXT_PUBLIC_CHAT_UPLOAD_FILE_CONFIG_TEMPLATE_JSON: ${NEXT_PUBLIC_CHAT_UPLOAD_FILE_CONFIG_TEMPLATE_JSON:-{}}
      NEXT_PUBLIC_CHAT_UPLOAD_FILE_HIDDEN_MESSAGE_TEMPLATE: '${NEXT_PUBLIC_CHAT_UPLOAD_FILE_HIDDEN_MESSAGE_TEMPLATE:-Let''s show the videos just uploaded {filenames}?}'
      NEXT_PUBLIC_CHAT_UPLOAD_FILE_METADATA_ENABLED: ${NEXT_PUBLIC_CHAT_UPLOAD_FILE_METADATA_ENABLED:-false}
      NEXT_PUBLIC_CHAT_API_CUSTOM_AGENT_PARAMS_JSON: ${NEXT_PUBLIC_CHAT_API_CUSTOM_AGENT_PARAMS_JSON:-{}}
      # === End of Chat Tab Configuration ===

      # === Alerts Tab Configuration ===
      NEXT_PUBLIC_ENABLE_ALERTS_TAB: ${NEXT_PUBLIC_ENABLE_ALERTS_TAB:-true}
      NEXT_PUBLIC_VST_API_URL: ${VSS_PUBLIC_HTTP_PROTOCOL}://${VSS_PUBLIC_HOST}:${VSS_PUBLIC_PORT}/vst/api
      NEXT_PUBLIC_MDX_WEB_API_URL: ${VSS_PUBLIC_HTTP_PROTOCOL}://${VSS_PUBLIC_HOST}:${VSS_PUBLIC_PORT}/video-analytics-api
      NEXT_PUBLIC_ALERTS_API_URL: ${VSS_PUBLIC_HTTP_PROTOCOL}://${VSS_PUBLIC_HOST}:${VSS_PUBLIC_PORT}/alert-bridge/api/v1
      NEXT_PUBLIC_ALERTS_TAB_ALERTS_FETCH_MAX_RESULT_SIZE: 100
      NEXT_PUBLIC_ALERTS_TAB_ALERTS_FETCH_DEFAULT_TIME_WINDOW_IN_MINUTES: 10
      NEXT_PUBLIC_ALERTS_TAB_DEFAULT_AUTO_REFRESH_IN_MILLISECONDS: 1000
      NEXT_PUBLIC_ALERTS_TAB_VERIFIED_FLAG_DEFAULT: ${NEXT_PUBLIC_ALERTS_TAB_VERIFIED_FLAG_DEFAULT:-false}
      NEXT_PUBLIC_ALERTS_TAB_ALERT_REPORT_PROMPT_TEMPLATE: "Generate a report for incident {incidentId} with sensor id {sensorId}."
      # Max search time limit (0 = unlimited, or use: 10m, 2h, 3d, 1w, 2M, 1y)
      NEXT_PUBLIC_ALERTS_TAB_MAX_SEARCH_TIME_LIMIT: 0
      NEXT_PUBLIC_ALERTS_TAB_MEDIA_WITH_OBJECTS_BBOX: ${NEXT_PUBLIC_ALERTS_TAB_MEDIA_WITH_OBJECTS_BBOX:-true}
      # === End of Alerts Tab Configuration ===

      # === Dashboard Tab Configuration ===
      NEXT_PUBLIC_ENABLE_DASHBOARD_TAB: ${NEXT_PUBLIC_ENABLE_DASHBOARD_TAB:-true}
      NEXT_PUBLIC_DASHBOARD_TAB_KIBANA_BASE_URL: ${VSS_PUBLIC_HTTP_PROTOCOL}://${VSS_PUBLIC_HOST}:${VSS_PUBLIC_PORT}/kibana
      # === End of Dashboard Tab Configuration ===

      # === SMC Map Tab Configuration ===
      NEXT_PUBLIC_ENABLE_MAP_TAB: ${NEXT_PUBLIC_ENABLE_MAP_TAB:-false}
      NEXT_PUBLIC_MAP_URL: ${NEXT_PUBLIC_MAP_URL:-http://${EXTERNAL_IP}:3002}
      # === End of SMC Map Tab Configuration ===

      # === Video Management Tab Configuration ===
      NEXT_PUBLIC_ENABLE_VIDEO_MANAGEMENT_TAB: ${NEXT_PUBLIC_ENABLE_VIDEO_MANAGEMENT_TAB:-true}
      NEXT_PUBLIC_VIDEO_MANAGEMENT_TAB_ADD_RTSP_ENABLE: ${NEXT_PUBLIC_VIDEO_MANAGEMENT_TAB_ADD_RTSP_ENABLE:-true}
      NEXT_PUBLIC_VIDEO_MANAGEMENT_VIDEO_UPLOAD_ENABLE: ${NEXT_PUBLIC_VIDEO_MANAGEMENT_VIDEO_UPLOAD_ENABLE:-true}
      # === End of Video Management Tab Configuration ===

      # === Search Tab Configuration ===
      NEXT_PUBLIC_ENABLE_SEARCH_TAB: ${NEXT_PUBLIC_ENABLE_SEARCH_TAB:-false}
      NEXT_PUBLIC_SEARCH_TAB_MEDIA_WITH_OBJECTS_BBOX: ${NEXT_PUBLIC_SEARCH_TAB_MEDIA_WITH_OBJECTS_BBOX:-true}
      # === End of Search Tab Configuration ===
